# Generated by Django 4.2.14 on 2024-07-16 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attachment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attachment',
            name='file_name',
        ),
        migrations.RemoveField(
            model_name='attachment',
            name='file_path',
        ),
        migrations.AddField(
            model_name='attachment',
            name='file',
            field=models.FileField(max_length=250, null=True, upload_to='attachments/'),
        ),
    ]
